apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-chatbot-deployment
  labels:
    app: llm-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-chatbot
  template:
    metadata:
      labels:
        app: llm-chatbot
    spec:
      containers:
      - name: llm-chatbot
        image: your_dockerhub_username/llm-chatbot:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/chatbot_db"
